default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  port: 3306
  host: <%= ENV['DB_HOST'] ||  'mysql'%>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || ENV['MYSQL_ROOT_PASSWORD'] %>
  database: app_test

production:
  <<: *default
  database: app_production
  socket: /cloudsql/<%= ENV['INSTANCE_CONNECTION_NAME'] %>
